spring.application.name=task-management

# Launch the default browser when starting the application in development mode
vaadin.launch-browser=true
# To improve the performance during development.
# For more information https://vaadin.com/docs/flow/spring/tutorial-spring-configuration.html#special-configuration-parameters
vaadin.allowed-packages=com.vaadin,org.vaadin,ch.martinelli.tm

spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanagement?reWriteBatchedInserts=true
spring.datasource.username=taskmanagement
spring.datasource.password=secret

spring.flyway.enabled=true
spring.jooq.sql-dialect=POSTGRES

# Log every SQL statement jOOQ executes (development only)
logging.level.org.jooq.tools.LoggerListener=DEBUG

# For encryption of JWT tokens
# Change this parameter in production servers, you can generate a key by running
# `openssl rand -base64 32`
# and then passing the result as a parameter or environment variable
jwt.auth.secret=7zTHNIXKEM4HJ1omvte6lQzz5HtAryzjqKvu7Ykh2Q0=

logging.level.org.atmosphere=warn
